# Trino coordinator-only (single-node) — phù hợp cho dev/demo
coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
discovery.uri=http://trino:8080
http-server.https.enabled=true
http-server.https.port=8443
http-server.https.keystore.path=/var/trino/security/trino-keystore.p12
http-server.https.keystore.key=${ENV:TRINO_KEYSTORE_PASSWORD}
http-server.authentication.type=PASSWORD
internal-communication.shared-secret=${ENV:TRINO_SHARED_SECRET}

# Giới hạn memory mỗi query để tránh OOM khi Spark chạy song song
query.max-memory-per-node=512MB
